# Use the base image
FROM cloudificando/spark-py:3.5.3

# Set a working directory (optional)
WORKDIR /opt/spark/scripts

# Copy your PySpark scripts into the container
COPY ./combopurifier-spark.py /opt/spark/scripts/
