apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: job-with-parameters
  namespace: spark-jobs
spec:
  sparkConf:
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.sql.extensions: "io.delta.sql.DeltaSparkSessionExtension"
    spark.sql.catalog.spark_catalog: "org.apache.spark.sql.delta.catalog.DeltaCatalog"
    spark.hadoop.fs.s3a.path.style.access: "True"
    spark.hadoop.fs.s3a.fast.upload: "True"
    spark.hadoop.fs.s3a.multipart.size: "104857600"
    spark.hadoop.fs.s3a.connection.maximum: "100"
    spark.hadoop.fs.s3a.endpoint: "http://minio.minio-dev.svc.cluster.local:9000"
    com.amazonaws.sdk.disableCertChecking: "False"
    spark.hadoop.fs.s3a.connection.ssl.strictverify: "False"
    spark.hadoop.fs.s3a.connection.ssl.enabled: "False"
    spark.hadoop.fs.s3a.ssl.enabled: "False"
  type: Python
  mode: cluster
#  image: "tiagotxm/owshq:spark-3.2.3-delta"
#  image: "leothenardo/spark-py-delta-s3a-combopurifier:3.5.3"
  image: "leothenardo/spark-combopurifier:1.0.0"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///opt/spark/scripts/combopurifier_spark.py"
#  mainApplicationFile: "s3a://spok-scripts/job-with-parameters.py"
  sparkVersion: "3.5.3"
  restartPolicy:
    type: Never
  deps:
    pyFiles:
      - local:///opt/spark/scripts/spark_session.py
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1024m"
    envFrom:
      - secretRef:
          name: s3-onprem-combopurifier
    serviceAccount: spark-operator-spark
    labels:
      version: "3.5.3"
  executor:
    cores: 1
    instances: 2
    memory: "1024m"
    envFrom:
      - secretRef:
          name: s3-onprem-combopurifier
    labels:
      version: "3.5.3"
