apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: brazilian-finder
  namespace: spark-jobs
spec:
  arguments:
    - job_name=brazilian-finder-job
    - source_bucket=s3a://lakehouse/bronze/combos/job-combopurifier-{{ id }}-delta
    - output_bucket=s3a://lakehouse/silver/combos/brazilian/job-combopurifier-{{ id }}
    - master_bucket=s3a://lakehouse/silver/combos/master-brazilian
    - brazilian_words_bucket=s3a://lakehouse/etc/brazilian_words.txt
  sparkConf:
    spark.plugins: "io.dataflint.spark.SparkDataflintPlugin"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.sql.extensions: "io.delta.sql.DeltaSparkSessionExtension"
    spark.sql.catalog.spark_catalog: "org.apache.spark.sql.delta.catalog.DeltaCatalog"
    spark.hadoop.fs.s3a.path.style.access: "True"
    spark.hadoop.fs.s3a.fast.upload: "True"
    spark.hadoop.fs.s3a.multipart.size: "104857600"
    spark.hadoop.fs.s3a.connection.maximum: "100"
    spark.hadoop.fs.s3a.endpoint: "http://minio.minio-dev.svc.cluster.local:9000"
    com.amazonaws.sdk.disableCertChecking: "False"
    spark.hadoop.fs.s3a.connection.ssl.strictverify: "False"
    spark.hadoop.fs.s3a.connection.ssl.enabled: "False"
    spark.hadoop.fs.s3a.ssl.enabled: "False"
    spark.eventLog.enabled: "True"
    spark.eventLog.dir: "s3a://logs/spark-history"

  type: Python
  mode: cluster
  image: "leothenardo/spark-brazilian-finder:786e07f2522173607ecb8190eb71d658d51be7b9"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///opt/spark/scripts/job.py"
  sparkVersion: "3.5.3"
  restartPolicy:
    type: Never
  deps:
    pyFiles:
      - local:///opt/spark/scripts/spark_session.py
#    packages:
#      - io.dataflint:spark_2.12:0.2.6
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1024m"
    envFrom:
      - secretRef:
          name: s3-onprem-combopurifier
    serviceAccount: spark-operator-spark
    labels:
      version: "3.5.3"
  executor:
    cores: 5
    instances: 2
    memory: "12000m" #12gb
    envFrom:
      - secretRef:
          name: s3-onprem-combopurifier
    labels:
      version: "3.5.3"
