executor: KubernetesExecutor

images:
  airflow:
    repository: cloudificando/airflow
    tag: "2.10.2"
    pullPolicy: IfNotPresent

config:
  core:
    dags_are_paused_at_creation: false
  kubernetes:
    namespace: "airflow"
    in_cluster: true
    delete_worker_pods: true
  logging:
    remote_logging: 'True'
    logging_level: 'INFO'
    remote_base_log_folder: 's3://combopurifier/airflow-logs' # Specify the S3 bucket used for logging
    remote_log_conn_id: 's3-onpremise' # Notice that this name is used in Step3 for creating connections through Airflow UI
    delete_worker_pods: 'False'
    encrypt_s3_logs: 'False'
data:
  metadataSecretName: airflow-secrets
postgresql:
  enabled: false
webserverSecretKeySecretName: airflow-secrets
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/leo-the-nardo/combopurifier.git"  # Replace with your Git repository
    # repo: "git@github.com:leo-the-nardo/combopurifier.git"  # Replace with your Git repository
    branch: "main"
    rev: "HEAD"
    depth: 1
    wait: 60
    subPath: "dags/"
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 30m
        memory: 64Mi
    credentialsSecret: "git-credentials"
    # sshKeySecret: "git-ssh-key-secret"
    # knownHosts: |
