# airflow-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: airflow
type: Opaque
stringData:
  fernet-key: "${FERNET_KEY}"
  webserver-secret-key: "${WEBSERVER_SECRET_KEY}"
  webserver-admin-password: "${WEBSERVER_ADMIN_PASSWORD}"
  git-username: "${GIT_USERNAME}"
  git-password: "${GIT_PASSWORD}"
