executor: KubernetesExecutor

images:
  airflow:
    repository: cloudificando/airflow
    tag: "2.10.2"
    pullPolicy: IfNotPresent

config:
  core:
    dags_are_paused_at_creation: false
  kubernetes:
    namespace: "airflow"
    in_cluster: true
    delete_worker_pods: true
data:
  metadataSecretName: airflow-secrets
postgresql:
  enabled: false
webserverSecretKeySecretName: airflow-secrets
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/leo-the-nardo/combopurifier.git"  # Replace with your Git repository
    # repo: "git@github.com:leo-the-nardo/combopurifier.git"  # Replace with your Git repository
    branch: "main"
    rev: "HEAD"
    depth: 1
    wait: 60
    subPath: "dags/"
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 30m
        memory: 64Mi
    credentialsSecret: "git-credentials"
    # sshKeySecret: "git-ssh-key-secret"
    # knownHosts: |
