---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: airflow-db
  namespace: airflow
spec:
  teamId: "airflow"
  volume:
    size: 10Gi
  numberOfInstances: 1  # Single-instance
  users:
    airflow: []  # Map of usernames to user flags (empty array if no flags)
  databases:
    airflow: airflow  # Database owned by 'airflow' user
  postgresql:
    version: "14"
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  allowedSourceRanges: []
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
