# https://stackoverflow.com/questions/68371840/unable-to-create-sparkapplications-on-kubernetes-cluster-using-sparkkubernetesop
# Role for spark-on-k8s-operator to create resources on cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-cluster-cr
  namespace: airflow
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
rules:
  - apiGroups:
      - sparkoperator.k8s.io
    resources:
      - sparkapplications
      - sparkapplications/status
    verbs:
      - '*'
---
# Allow airflow-worker service account access for spark-on-k8s
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-spark-crb
  namespace: airflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spark-cluster-cr
subjects:
  - kind: ServiceAccount
    name: airflow-cluster
    namespace: airflow
  - kind: ServiceAccount
    name: airflow-scheduler
    namespace: airflow
  - kind: ServiceAccount
    name: airflow-worker
    namespace: airflow
  - kind: ServiceAccount
    name: airflow-triggerer
    namespace: airflow
---
# "system:serviceaccount:airflow:airflow-worker\" cannot list resource \"pods\" in API group \"\" in the namespace \"processing\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}   │
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: spark-jobs
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods","pods/*", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: spark-jobs
subjects:
  - kind: ServiceAccount
    name: airflow-worker
    namespace: airflow
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

# #helm repo add apache-airflow https://airflow.apache.org
# #helm repo update
# # airflow-rbac.yaml
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: airflow
#   namespace: airflow

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: airflow-role
#   namespace: airflow
# rules:
#   - apiGroups: ["", "apps", "batch"]
#     resources: ["pods", "pods/log", "pods/exec", "deployments", "jobs"]
#     verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: airflow-rolebinding
#   namespace: airflow
# subjects:
#   - kind: ServiceAccount
#     name: airflow
#     namespace: airflow
# roleRef:
#   kind: Role
#   name: airflow-role
#   apiGroup: rbac.authorization.k8s.io

# ---
# # airflow-networkpolicy.yaml
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: airflow-network-policy
#   namespace: airflow
# spec:
#   podSelector:
#     matchLabels:
#       component: airflow
#   policyTypes:
#     - Ingress
#     - Egress
#   ingress:
#     - from:
#         - podSelector:
#             matchLabels:
#               component: airflow
#       ports:
#         - protocol: TCP
#           port: 8080
#   egress:
#     - to:
#         - podSelector:
#             matchLabels:
#               component: airflow
#       ports:
#         - protocol: TCP
#           port: 5432
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: airflow-web
  namespace: gateway
  annotations:
    konghq.com/strip-path: "true"
spec:
  parentRefs:
    - name: kong
      namespace: gateway
  hostnames:
    - airflow.cloudificando.corp
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: airflow-webserver
          port: 8080
          kind: Service
          namespace: airflow
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: airflow-web
  namespace: airflow
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: gateway
  to:
    - group: ""
      kind: Service
